### PR TITLE
Updating default/main.yaml configuration

### PR DESCRIPTION
**Pull request by smerck**
# Overview

Following discussion with @dkaranth123 and reviewing the configuration in cloudbrink/CIS-Ubuntu-20.04-Ansible-Edge repo. This PR adds the changes that are being used for securing the edges. 

- disables root pw
- disables FAT fs mounts
- disables firewall
- removes root from allowed users

# TODO

There are a few outstanding tasks/changes that still need to be addressed:
- In cloudbrink/CIS-Ubuntu-20.04-Ansible-Edge, part of section 1.4.1 is commented out. Need clarification on why that is because i've not had issues runnning this part of the playbook.
- After this merges, will need to update the git submodule in cloudbrink/connector-image & cloudbrink/edge-image.
- After these are done, will fetch/merge upstream commits (currently 18 commits behind upstream).

### CODE REVIEW

**Comment by smerck** [comment]
Section 1.9 has been skipped in the packer provisioner (https://github.com/cloudbrink/connector-image/pull/9/files#diff-2064d954b17de878e096ba762d89846bd961136972accdd068147470929afe4cR133) rather than commenting out section 1.9 in the playbook. I believe this is ultimately cleaner and will make it easier to pull from upstream.

**Comment by smerck** [comment]
Just merging this PR since i've waited for 2 weeks so far.

**Comment by dkaranth123** [comment]
> /cc @dkaranth123 -- let me know if there's anything you think we should change here. Let me know if you have any clarifications/thoughts around section 1.4.1. Thanks!

Sorry I got to this late. The reason why this was commented was because it was observed that executing this task took so long and would hold up script completion. If you did not see this happening, I think is okay having it here.

**Pull request merged**
